# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: no-commit-to-branch
-   repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
    -   id: cpplint
        args: [--linelength=100, "--filter=-runtime/references,-readability/braces,-build/include,-build/c++11"]
        types_or: [c, c++, cuda]
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4 # Ruff version.
    hooks:
      - id: ruff # Run the linter for Python.
        args: ["--ignore=E402"]  # Ignore E402 error "Module level import not at top of file"
      - id: ruff-format # Run the formatter for Python.

#   # Use black to clean code in python and jupyter notebook cells
# -   repo: https://github.com/psf/black
#     rev: 23.3.0
#     hooks:
#       - id: black
#         files: examples/eurec4a1d
#         args: [--config=./pyproject.toml]

# -   repo: meta
#     hooks:
#     -   id: identity
#         name: identity (filtered)
#         # files: ^web\/(modules\/custom|themes\/my_theme)\/.+.php$
