name: cleoenv
channels:
    - conda-forge
dependencies:
    - python>=3.13
    - pytest
    # packages to install CLEO pySD
    - pip
    - numpy
    - scipy
    - matplotlib
    - netcdf4
    - xarray
    - sphinx
    - furo
    - sphinx_copybutton
    - sphinxcontrib-bibtex
    - breathe
    - numpy
    - scipy
    - matplotlib
    - netcdf4
    - xarray
    - awkward
    - random
    - struct
    - zarr
    - doxygen>=1.10.0
    - pip
    - pip:
      - -r requirements.txt
