name: CLEO-install-env
channels:
  - defaults
#   - conda-forge
dependencies:
    - python>=3.12
    - pytest
    - sphinx
    - furo
    - sphinx_copybutton
    - sphinxcontrib-bibtex
    - breathe
    - numpy
    - scipy
    - matplotlib
    - netcdf4
    - xarray
    - awkward
    - random
    - struct
    - zarr
