name: CLEO-install-env
channels:
  - defaults
#   - conda-forge
dependencies:
    - python>=3.12
    - pytest
    # packages to install CLEO pySD
    - pip
    - numpy
    - scipy
    - matplotlib
    - netcdf4
    - xarray
