# ----- CLEO -----
# File: eurec4a1d_config.yaml
# Project: config
# Created Date: Thursday 18th April 2024
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Thursday 18th April 2024
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for CLEO eurec4a 1-D rainshaft example.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py"),
# and so can the thermodynamics files when using coupled thermodynamics "fromfile".
#

### SDM Runtime Parameters ###
domain:
  nspacedims: 1
  ngbxs: 10
  maxnsupers: 10000
timesteps:
  CONDTSTEP: 0.1
  COLLTSTEP: 1
  MOTIONTSTEP: 2
  COUPLTSTEP: 1200
  OBSTSTEP: 2
  T_END: 1200
inputfiles:
  constants_filename: /home/m/m301096/CLEO/libs/cleoconstants.hpp
  grid_filename: None
initsupers:
  type: frombinary
  initsupers_filename: None
  initnsupers: 512
outputdata:
  setup_filename: None
  stats_filename: None
  zarrbasedir: None
  maxchunk: 2500000
microphysics:
  condensation:
    do_alter_thermo: false
    niters: 10
    SUBTSTEP: 0.1
    rtol: 0.03
    atol: 0.03
coupled_dynamics:
  type: fromfile
  press: None
  temp: None
  qvap: None
  qcond: None
  wvel: None
  thermo: None
boundary_conditions:
  type: addsupersatdomaintop
  COORD3LIM: 1000
  newnsupers: 512
  DRYRADIUS: 1e-09
  MINRADIUS: 0.1
  MAXRADIUS: 1
  NUMCONC_a: 1
  GEOMEAN_a: 1
  geosigma_a: 1
  NUMCONC_b: 1
  GEOMEAN_b: 1
  geosigma_b: 1
